### PR TITLE
Added support for Swedish

### PR DESCRIPTION
**Pull request by JoelESvensson**

### CODE REVIEW

**Comment by RyanThompson** [comment]
Killer! Thank you!

**Comment by RyanThompson** [comment]
And keep em coming lol

**Comment by JoelESvensson** [comment]
hehe, will do :) I'm stuck translating right now because I don't know why some field labels get nulled when I select Swedish. Seems to be a problem with the fallback language. Might be something with my configuration. I'll get back to this as soon as I know more about it. It might be reproducible if you just select Swedish and try to create a new post type.

**Comment by RyanThompson** [comment]
Will do - I will take a look later tonight. I am wondering .. I think the fallback_locale should be a separate value then the default locale.

Fallback -> Default -> User Choice

Currently it's

Default (IS fallback) -> User Choice

So if fallback is SE.. shit's missing. Where as it should be the native shipped language (EN) so everything has at least AH value.

**Comment by JoelESvensson** [comment]
Okay! For your interest I found out when debugging that the 'fallback_locale' variables are set to Swedish

**Comment by RyanThompson** [comment]
Ya I will fix this later tonight!

**Comment by JoelESvensson** [comment]
Great!!

**Pull request merged**
