### PR TITLE
Updated PostResolver to resolve posts where the path is empty

### PR DESCRIPTION
**Pull request by daviesgeek**
For #16 

I'm not sure if this too simple of an approach or not. Am I missing pieces or will this be enough?

The routes will all map correctly, so no changes needed there; all that needed to be changed was the resolver

### CODE REVIEW

**Comment by daviesgeek** [comment]
Okay found a bug (or a feature?). When `module` is empty, `/` resolves a list of posts and potentially overrides other `/` routes

**Comment by RyanThompson** [comment]
Ya.. That's not really intended and one of the many reasons that the module segment is added there.

Idk man Im not feeling that great about this. I think you might be better off achieving this yourself / independently.

**Comment by daviesgeek** [comment]
Yup yup. I totally get it and feel the same way. I can close this if you want, since it really isn't going to work…

**Comment by RyanThompson** [comment]
Ya - i think we'll keep this in mind as a feature but I think it is too far away from core options / configurable. At least we know we can do it!

**Comment by daviesgeek** [comment]
Sounds good!

**Pull request closed without merging**
